/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gretchen (https://sketchfab.com/samarui)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/jacket-agc-6e4321cb0d534debaa4f959dc83bae8e
title: Jacket - AGC
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Jacket({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/jacket.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={40}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Jacket} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jacket.glb')
