# Generated by Django 4.0.3 on 2022-03-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_brand_order_user_product_product_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='User_account_hash_code',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_account',
            name='User_account_salt',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images_url', models.TextField()),
                ('Images_physical_path', models.TextField()),
                ('Images_size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Images_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.category')),
                ('Images_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.product')),
            ],
        ),
    ]
