# Generated by Django 4.0.3 on 2022-03-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_regestrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regestrations',
        ),
    ]
