# Generated by Django 4.0.3 on 2022-03-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0005_delete_regestrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_product',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='Product_type_product',
        ),
        migrations.AddField(
            model_name='product',
            name='Category_product',
            field=models.ManyToManyField(to='e_commerce.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_type_product',
            field=models.ManyToManyField(to='e_commerce.product_type'),
        ),
    ]
