# Generated by Django 4.0.3 on 2022-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0006_remove_category_category_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_code',
            new_name='Transaction_code',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_content',
            new_name='Transaction_content',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_mode',
            new_name='Transaction_mode',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_order',
            new_name='Transaction_order',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_status',
            new_name='Transaction_status',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='Transaction_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_user',
            new_name='Transaction_user',
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('Size_product', models.ManyToManyField(to='e_commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_name', models.CharField(max_length=75)),
                ('Color_product', models.ManyToManyField(to='e_commerce.product')),
            ],
        ),
    ]
