/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SmartPlan (https://sketchfab.com/SmartPlan)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/black-dress-5079978e8e39489db88e0232d224117a
title: Black Dress
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Dress({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/dress.glb')
  return (
    <group ref={group} {...props} dispose={null} scale = {.5}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('/dress.glb')
